# PostgreSQL. Versions 8.2 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: locatable_development

test:
  <<: *default
  database: locatable_test

production:
  <<: *default
  database: locatable_production
  username: locatable
  password: <%= ENV['PET-BACKEND_DATABASE_PASSWORD'] %>
